# ============================================
# ALACRITTY CONFIG - TOKYO NIGHT THEME
# ============================================

# Window Settings
[window]
opacity = 0.85  # Ajuste entre 0.0 (transparente) e 1.0 (opaco)
padding.x = 10
padding.y = 10
decorations = "full"  # full, none, transparent, buttonless
dynamic_title = true
dynamic_padding = false

# Blur (se o compositor suportar)
blur = true

# Font Configuration
[font]
normal.family = "JetBrainsMono Nerd Font"
normal.style = "Regular"
bold.family = "JetBrainsMono Nerd Font"
bold.style = "Bold"
italic.family = "JetBrainsMono Nerd Font"
italic.style = "Italic"
size = 11.0

# Cursor
[cursor]
style.shape = "Block"
style.blinking = "On"
blink_interval = 750
unfocused_hollow = true

# Shell
[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

# ============================================
# TOKYO NIGHT COLOR SCHEME
# ============================================

[colors.primary]
background = "#1a1b26"
foreground = "#c0caf5"

[colors.normal]
black = "#15161e"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#a9b1d6"

[colors.bright]
black = "#414868"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#c0caf5"

# Selection colors
[colors.selection]
text = "CellBackground"
background = "#33467c"

# Cursor colors
[colors.cursor]
text = "#1a1b26"
cursor = "#c0caf5"

# Vi mode cursor
[colors.vi_mode_cursor]
text = "#1a1b26"
cursor = "#c0caf5"

# Search colors
[colors.search.matches]
foreground = "#1a1b26"
background = "#e0af68"

[colors.search.focused_match]
foreground = "#1a1b26"
background = "#9ece6a"

# Hints
[colors.hints.start]
foreground = "#1a1b26"
background = "#e0af68"

[colors.hints.end]
foreground = "#1a1b26"
background = "#9ece6a"

# Line indicator
[colors.line_indicator]
foreground = "None"
background = "None"

# Footer bar
[colors.footer_bar]
foreground = "#1a1b26"
background = "#a9b1d6"

# ============================================
# SCROLLING
# ============================================

[scrolling]
history = 10000
multiplier = 3

# ============================================
# BELL
# ============================================

[bell]
animation = "EaseOutExpo"
duration = 0
color = "#ffffff"

# ============================================
# MOUSE
# ============================================

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Right"
action = "PasteSelection"

# ============================================
# KEY BINDINGS
# ============================================

[keyboard]
bindings = [
    { key = "V", mods = "Control|Shift", action = "Paste" },
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "Plus", mods = "Control", action = "IncreaseFontSize" },
    { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
    { key = "Key0", mods = "Control", action = "ResetFontSize" },
]

[terminal]
